require File.expand_path('../boot', __FILE__)

require 'rails/all'
require 'csv'

if defined?(Bundler)
  # If you precompile assets before deploying to production, use this line
  Bundler.require(*Rails.groups(:assets => %w(development test)))
  # If you want your assets lazily compiled in production, use this line
  # Bundler.require(:default, :assets, Rails.env)
end

module SimonDeCirene
  class Application < Rails::Application

    # don't generate RSpec tests for views and helpers
    config.generators do |g|
      
      g.test_framework :rspec, fixture: true
      g.fixture_replacement :factory_girl, dir: 'spec/factories'
      
      
      g.view_specs false
      g.helper_specs false
    end

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Custom directories with classes and modules you want to be autoloadable.
    # config.autoload_paths += %W(#{config.root}/extras)
    config.autoload_paths += %W(#{config.root}/lib)


    # Only load the plugins named here, in the order given (default is alphabetical).
    # :all can be used as a placeholder for all plugins not explicitly named.
    # config.plugins = [ :exception_notification, :ssl_requirement, :all ]

    # Activate observers that should always be running.
    # config.active_record.observers = :cacher, :garbage_collector, :forum_observer

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Configure the default encoding used in templates for Ruby 1.9.
    config.encoding = "utf-8"

    # Configure sensitive parameters which will be filtered from the log file.
    config.filter_parameters += [:password, :password_confirmation]

    # Enable escaping HTML in JSON.
    config.active_support.escape_html_entities_in_json = true

    # Use SQL instead of Active Record's schema dumper when creating the database.
    # This is necessary if your schema can't be completely dumped by the schema dumper,
    # like if you have constraints or database-specific column types
    # config.active_record.schema_format = :sql

    # Enforce whitelist mode for mass assignment.
    # This will create an empty whitelist of attributes available for mass-assignment for all models
    # in your app. As such, your models will need to explicitly whitelist or blacklist accessible
    # parameters by using an attr_accessible or attr_protected declaration.
    config.active_record.whitelist_attributes = true

    # Enable the asset pipeline
    config.assets.enabled = true

    # Version of your assets, change this if you want to expire all your assets
    config.assets.version = '1.0'

    COMUNAS = [
      'Arica',
      'Algarrobo',
      'Alhue',
      'Alto Biobio',
      'Alto Del Carmen',
      'Alto Hospicio',
      'Ancud',
      'Andacollo',
      'Angol',
      'Antofagasta',
      'Antuco',
      'Arauco',
      'Aysen',
      'Buin',
      'Bulnes',
      'Cabildo',
      'Cabo De Hornos',
      'Cabrero',
      'Calama',
      'Calbuco',
      'Caldera',
      'Calera De Tango',
      'Calle Larga',
      'Camarones',
      'Camina',
      'Canela',
      'Canete',
      'Carahue',
      'Cartagena',
      'Casablanca',
      'Castro',
      'Catemu',
      'Cauquenes',
      'Cerrillos',
      'Cerro Navia',
      'Chaiten',
      'Chanaral',
      'Chanco',
      'Chepica',
      'Chiguayante',
      'Chile Chico',
      'Chillan Viejo',
      'Chillan',
      'Chimbarongo',
      'Cholchol',
      'Chonchi',
      'Cisnes',
      'Cobquecura',
      'Cochamo',
      'Cochrane',
      'Codegua',
      'Coelemu',
      'Coihueco',
      'Coinco',
      'Colbun',
      'Colchane',
      'Colina',
      'Collipulli',
      'Coltauco',
      'Combarbala',
      'Concepcion',
      'Conchali',
      'Concon',
      'Constitucion',
      'Contulmo',
      'Copiapo',
      'Coquimbo',
      'Coronel',
      'Corral',
      'Coyhaique',
      'Cunco',
      'Curacautin',
      'Curacavi',
      'Curaco De Velez',
      'Curanilahue',
      'Curarrehue',
      'Curepto',
      'Curico',
      'Dalcahue',
      'Diego De Almagro',
      'Donihue',
      'El Bosque',
      'El Carmen',
      'El Monte',
      'El Quisco',
      'El Tabo',
      'Empedrado',
      'Ercilla',
      'Estacion Central',
      'Florida',
      'Freire',
      'Freirina',
      'Fresia',
      'Frutillar',
      'Futaleufu',
      'Futrono',
      'Galvarino',
      'General Lagos',
      'Gorbea',
      'Graneros',
      'Guaitecas',
      'Hijuelas',
      'Hualaihue',
      'Hualane',
      'Hualpen',
      'Hualqui',
      'Huara',
      'Huasco',
      'Huechuraba',
      'Illapel',
      'Independencia',
      'Iquique',
      'Isla De Maipo',
      'Isla De Pascua',
      'Juan Fernandez',
      'La Calera',
      'La Cisterna',
      'La Cruz',
      'La Estrella',
      'La Florida',
      'La Granja',
      'La Higuera',
      'La Ligua',
      'La Pintana',
      'La Reina',
      'La Serena',
      'La Union',
      'Lago Ranco',
      'Lago Verde',
      'Laguna Blanca',
      'Laja',
      'Lampa',
      'Lanco',
      'Las Cabras',
      'Las Condes',
      'Lautaro',
      'Lebu',
      'Licanten',
      'Limache',
      'Linares',
      'Litueche',
      'Llanquihue',
      'Llay-Llay',
      'Lo Barnechea',
      'Lo Espejo',
      'Lo Prado',
      'Lolol',
      'Loncoche',
      'Longavi',
      'Lonquimay',
      'Los Alamos',
      'Los Andes',
      'Los Angeles',
      'Los Lagos',
      'Los Muermos',
      'Los Sauces',
      'Los Vilos',
      'Lota',
      'Lumaco',
      'Machali',
      'Macul',
      'Mafil',
      'Maipu',
      'Malloa',
      'Marchigue',
      'Maria Elena',
      'Maria Pinto',
      'Mariquina',
      'Maule',
      'Maullin',
      'Mejillones',
      'Melipeuco',
      'Melipilla',
      'Molina',
      'Monte Patria',
      'Mulchen',
      'Nacimiento',
      'Nancagua',
      'Natales',
      'Navidad',
      'Negrete',
      'Ninhue',
      'Niquen',
      'Nogales',
      'Nueva Imperial',
      'Nunoa',
      'Ohiggins',
      'Olivar',
      'Ollague',
      'Olmue',
      'Osorno',
      'Ovalle',
      'Padre Hurtado',
      'Padre Las Casas',
      'Paihuano',
      'Paillaco',
      'Paine',
      'Palena',
      'Palmilla',
      'Panguipulli',
      'Panquehue',
      'Papudo',
      'Paredones',
      'Parral',
      'Pedro Aguirre Cerda',
      'Pelarco',
      'Pelluhue',
      'Pemuco',
      'Penaflor',
      'Penalolen',
      'Pencahue',
      'Penco',
      'Peralillo',
      'Perquenco',
      'Petorca',
      'Peumo',
      'Pica',
      'Pichidegua',
      'Pichilemu',
      'Pinto',
      'Pirque',
      'Pitrufquen',
      'Placilla',
      'Portezuelo',
      'Porvenir',
      'Pozo Almonte',
      'Primavera',
      'Providencia',
      'Puchuncavi',
      'Pucon',
      'Pudahuel',
      'Puente Alto',
      'Puerto Montt',
      'Puerto Octay',
      'Puerto Varas',
      'Pumanque',
      'Punitaqui',
      'Punta Arenas',
      'Puqueldon',
      'Puren',
      'Purranque',
      'Putaendo',
      'Putre',
      'Puyehue',
      'Queilen',
      'Quellon',
      'Quemchi',
      'Quilaco',
      'Quilicura',
      'Quilleco',
      'Quillon',
      'Quillota',
      'Quilpue',
      'Quinchao',
      'Quinta De Tilcoco',
      'Quinta Normal',
      'Quintero',
      'Quirihue',
      'Rancagua',
      'Ranquil',
      'Rauco',
      'Recoleta',
      'Renaico',
      'Renca',
      'Rengo',
      'Requinoa',
      'Retiro',
      'Rinconada',
      'Rio Bueno',
      'Rio Claro',
      'Rio Hurtado',
      'Rio Ibanez',
      'Rio Negro',
      'Rio Verde',
      'Romeral',
      'Saavedra',
      'Sagrada Familia',
      'Salamanca',
      'San Antonio',
      'San Bernardo',
      'San Carlos',
      'San Clemente',
      'San Esteban',
      'San Fabian',
      'San Felipe',
      'San Fernando',
      'San Francisco De Mostazal',
      'San Gregorio',
      'San Ignacio',
      'San Javier',
      'San Joaquin',
      'San Jose De Maipo',
      'San Juan De La Costa',
      'San Miguel',
      'San Nicolas',
      'San Pablo',
      'San Pedro De Atacama',
      'San Pedro De La Paz',
      'San Pedro',
      'San Rafael',
      'San Ramon',
      'San Rosendo',
      'San Vicente',
      'Santa Barbara',
      'Santa Cruz',
      'Santa Juana',
      'Santa Maria',
      'Santiago Oeste',
      'Santiago Sur',
      'Santiago',
      'Santo Domingo',
      'Sierra Gorda',
      'Talagante',
      'Talca',
      'Talcahuano',
      'Taltal',
      'Temuco',
      'Teno',
      'Teodoro Schmidt',
      'Tierra Amarilla',
      'Til-Til',
      'Timaukel',
      'Tirua',
      'Tocopilla',
      'Tolten',
      'Tome',
      'Torres Del Paine',
      'Tortel',
      'Traiguen',
      'Trehuaco',
      'Tucapel',
      'Valdivia',
      'Vallenar',
      'Valparaiso',
      'Vichuquen',
      'Victoria',
      'Vicuna',
      'Vilcun',
      'Villa Alegre',
      'Villa Alemana',
      'Villarrica',
      'Vina Del Mar',
      'Vitacura',
      'Yerbas Buenas',
      'Yumbel',
      'Yungay',
      'Zapallar'
    ]
  end
end
