COMUNAS = [
'Arica',
'Camarones',
'Iquique',
'Pica',
'Pozo Almonte',
'Huara',
'Camina',
'Colchane',
'Alto Hospicio',
'Putre',
'General Lagos',
'Tocopilla',
'Maria Elena',
'Antofagasta',
'Taltal',
'Mejillones',
'Sierra Gorda',
'Calama',
'Ollague',
'San Pedro De Atacama',
'Chanaral',
'Diego De Almagro',
'Copiapo',
'Caldera',
'Tierra Amarilla',
'Vallenar',
'Freirina',
'Huasco',
'Alto Del Carmen',
'La Serena',
'La Higuera',
'Coquimbo',
'Andacollo',
'Vicuna',
'Paihuano',
'Ovalle',
'Monte Patria',
'Punitaqui',
'Combarbala',
'Rio Hurtado',
'Illapel',
'Salamanca',
'Los Vilos',
'Canela',
'Isla De Pascua',
'La Ligua',
'Petorca',
'Cabildo',
'Zapallar',
'Papudo',
'Valparaiso',
'Vina Del Mar',
'Villa Alemana',
'Quilpue',
'Casablanca',
'Quintero',
'Puchuncavi',
'Juan Fernandez',
'Concon',
'San Antonio',
'Santo Domingo',
'Cartagena',
'El Tabo',
'El Quisco',
'Algarrobo',
'Quillota',
'Nogales',
'Hijuelas',
'La Calera',
'La Cruz',
'Limache',
'Olmue',
'San Felipe',
'Panquehue',
'Catemu',
'Putaendo',
'Santa Maria',
'Llay-Llay',
'Los Andes',
'Calle Larga',
'San Esteban',
'Rinconada',
'Rancagua',
'Machali',
'Graneros',
'San Francisco De Mostazal',
'Donihue',
'Coltauco',
'Codegua',
'Peumo',
'Las Cabras',
'San Vicente',
'Pichidegua',
'Rengo',
'Requinoa',
'Olivar',
'Malloa',
'Coinco',
'Quinta De Tilcoco',
'San Fernando',
'Chimbarongo',
'Nancagua',
'Placilla',
'Santa Cruz',
'Lolol',
'Palmilla',
'Peralillo',
'Chepica',
'Pumanque',
'Pichilemu',
'Navidad',
'Litueche',
'La Estrella',
'Marchigue',
'Paredones',
'Curico',
'Teno',
'Romeral',
'Rauco',
'Licanten',
'Vichuquen',
'Hualane',
'Molina',
'Sagrada Familia',
'Talca',
'San Clemente',
'Pelarco',
'Rio Claro',
'Pencahue',
'Maule',
'Curepto',
'Constitucion',
'Empedrado',
'San Rafael',
'Linares',
'Yerbas Buenas',
'Colbun',
'Longavi',
'Parral',
'Retiro',
'Villa Alegre',
'San Javier',
'Cauquenes',
'Pelluhue',
'Chanco',
'Chillan',
'Pinto',
'Coihueco',
'Quirihue',
'Ninhue',
'Portezuelo',
'Cobquecura',
'Trehuaco',
'San Carlos',
'Niquen',
'San Fabian',
'San Nicolas',
'Bulnes',
'San Ignacio',
'Quillon',
'Yungay',
'Pemuco',
'El Carmen',
'Ranquil',
'Coelemu',
'Chillan Viejo',
'Concepcion',
'Penco',
'Hualqui',
'Florida',
'Tome',
'Talcahuano',
'Coronel',
'Lota',
'Santa Juana',
'San Pedro De La Paz',
'Chiguayante',
'Hualpen',
'Arauco',
'Curanilahue',
'Lebu',
'Los Alamos',
'Canete',
'Contulmo',
'Tirua',
'Los Angeles',
'Santa Barbara',
'Laja',
'Quilleco',
'Nacimiento',
'Negrete',
'Mulchen',
'Quilaco',
'Yumbel',
'Cabrero',
'San Rosendo',
'Tucapel',
'Antuco',
'Alto Biobio',
'Angol',
'Puren',
'Los Sauces',
'Renaico',
'Collipulli',
'Ercilla',
'Traiguen',
'Lumaco',
'Victoria',
'Curacautin',
'Lonquimay',
'Temuco',
'Vilcun',
'Freire',
'Cunco',
'Lautaro',
'Perquenco',
'Galvarino',
'Nueva Imperial',
'Carahue',
'Saavedra',
'Pitrufquen',
'Gorbea',
'Tolten',
'Loncoche',
'Villarrica',
'Pucon',
'Melipeuco',
'Curarrehue',
'Teodoro Schmidt',
'Padre Las Casas',
'Cholchol',
'Valdivia',
'Mariquina',
'Lanco',
'Los Lagos',
'Futrono',
'Corral',
'Mafil',
'Panguipulli',
'La Union',
'Paillaco',
'Rio Bueno',
'Lago Ranco',
'Osorno',
'San Pablo',
'Puerto Octay',
'Puyehue',
'Rio Negro',
'Purranque',
'San Juan De La Costa',
'Puerto Montt',
'Cochamo',
'Puerto Varas',
'Fresia',
'Frutillar',
'Llanquihue',
'Maullin',
'Los Muermos',
'Calbuco',
'Castro',
'Chonchi',
'Queilen',
'Quellon',
'Puqueldon',
'Ancud',
'Quemchi',
'Dalcahue',
'Curaco De Velez',
'Quinchao',
'Chaiten',
'Hualaihue',
'Futaleufu',
'Palena',
'Aysen',
'Cisnes',
'Guaitecas',
'Chile Chico',
'Rio Ibanez',
'Cochrane',
'Ohiggins',
'Tortel',
'Coyhaique',
'Lago Verde',
'Natales',
'Torres Del Paine',
'Rio Verde',
'San Gregorio',
'Punta Arenas',
'Laguna Blanca',
'Porvenir',
'Primavera',
'Timaukel',
'Cabo De Hornos',
'Santiago',
'Santiago Oeste',
'Santiago Sur',
'Recoleta',
'Independencia',
'Quinta Normal',
'Maipu',
'Pudahuel',
'Renca',
'Quilicura',
'Conchali',
'Lo Prado',
'Cerro Navia',
'Estacion Central',
'Huechuraba',
'Cerrillos',
'Colina',
'Lampa',
'Til-Til',
'Talagante',
'Isla De Maipo',
'El Monte',
'Penaflor',
'Padre Hurtado',
'Melipilla',
'Maria Pinto',
'Curacavi',
'San Pedro',
'Alhue',
'Providencia',
'Nunoa',
'Las Condes',
'La Florida',
'La Reina',
'Macul',
'Penalolen',
'Vitacura',
'Lo Barnechea',
'San Miguel',
'La Cisterna',
'La Granja',
'San Ramon',
'La Pintana',
'Pedro Aguirre Cerda',
'San Joaquin',
'Lo Espejo',
'El Bosque',
'Puente Alto',
'Pirque',
'San Jose De Maipo',
'San Bernardo',
'Calera De Tango',
'Buin',
'Paine'
]